create table if not exists public.keg_pours (
  id bigint generated by default as identity primary key,
  reading_id bigint references public.keg_readings(id) on delete set null,
  poured_at timestamptz not null default now(),
  ounces numeric(6,2) not null check (ounces >= 1 and ounces <= 64),
  beer_oz_after numeric(7,2)
);

create index if not exists keg_pours_poured_at_idx on public.keg_pours (poured_at desc);
alter table public.keg_pours enable row level security;

create policy "household members can read keg pours"
on public.keg_pours for select to authenticated using (true);

revoke insert, update, delete on public.keg_pours from anon, authenticated;
grant select on public.keg_pours to authenticated;
