create table if not exists public.keg_changes (
  id bigint generated by default as identity primary key,
  reading_id bigint references public.keg_readings(id) on delete set null,
  changed_at timestamptz not null default now(),
  starting_ounces numeric(7,2),
  starting_percent numeric(5,2)
);

create index if not exists keg_changes_changed_at_idx on public.keg_changes (changed_at desc);
alter table public.keg_changes enable row level security;

create policy "household members can read keg changes"
on public.keg_changes for select to authenticated using (true);

revoke insert, update, delete on public.keg_changes from anon, authenticated;
grant select on public.keg_changes to authenticated;
