create table if not exists public.keg_readings (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null default now(),
  payload jsonb not null
);

alter table public.keg_readings enable row level security;

create policy "household members can read keg status"
on public.keg_readings for select to authenticated using (true);

create index if not exists keg_readings_recorded_at_idx
on public.keg_readings (recorded_at desc);

revoke insert, update, delete on public.keg_readings from anon, authenticated;
grant select on public.keg_readings to authenticated;
